name: test

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "nightly"
          target: "wasm32-unknown-unknown"

      - name: install wasm-pack
        shell: "bash"
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall wasm-pack -y --force
          wasm-pack build --release --target web --out-dir ./web
