name: test

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "nightly"
      - name: install wasm-pack
        shell: "bash"
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack -y
          export PATH="$HOME/.cargo/bin:$PATH"
          echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          /home/runner/.cargo/bin/wasm-pack build --release --target web --out-dir ./web
